### ISSUE TITLE
ASIMD: Element-wise tests are failing

### ISSUE THREAD

**Issue by breuera** [libxsmm/libxsmm#735]
The element-wise tests are failing when using N1.
Last successful run was on January 10 ([03f0e9c](https://github.com/libxsmm/libxsmm/commit/03f0e9c27cfb17e24ffe9d2d88ceaf3d2c3aaf88)).

This is the pipeline:

```
steps:
  - command:
      - make PLATFORM=1 JIT=1 WERROR=1 BLAS=0 -j
      - cd samples/eltwise/
      - make PLATFORM=1 JIT=1 WERROR=1 BLAS=0 -j
      - ./run_test.sh
      - cd ../..
    label: ":pipeline: eltwise"
```

Here's the output:
[0185cdc7-2fee-4482-9bfb-887fbc12a090.log](https://github.com/libxsmm/libxsmm/files/10465870/0185cdc7-2fee-4482-9bfb-887fbc12a090.log)

**Comment by egeor** [comment]
Commit 2d69da45119769fc7fd052b3288ecb7098853462 should fix these issues. Please check and close the issue if this is true.

**Comment by hfp** [comment]
I added Eltwise tests (`SSIZE=4`) to our AArch64 baseline system, and they still fail.

**Comment by breuera** [comment]
> I added Eltwise tests (`SSIZE=4`) to our AArch64 baseline system, and they still fail.

Still fails in my tests (ASIMD and SVE512) as well, here is https://github.com/libxsmm/libxsmm/commit/2d69da45119769fc7fd052b3288ecb7098853462:

[libxsmm-asimd_build_754_pipeline-eltwise.log](https://github.com/libxsmm/libxsmm/files/10519668/libxsmm-asimd_build_754_pipeline-eltwise.log)
[libxsmm-sve512_build_738_pipeline-eltwise.log](https://github.com/libxsmm/libxsmm/files/10519667/libxsmm-sve512_build_738_pipeline-eltwise.log)

**Comment by hfp** [comment]
Re:SVE512 (A64FX), we only validate manually (not continuously). It's probably a matter of updating our ALLOW-list after revamping the Eltwise coverage (#724).

**Comment by breuera** [comment]
[f5f60e4](https://github.com/libxsmm/libxsmm/commit/f5f60e436613348ab83dc84b65837e34fdc201c9) passed, closing the issue.
